# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Ziming Li (李子铭)
title: PhD candidate at University of Amsterdam
email: cszimingli@gmail.com
website: zimingli.info

# Social links
twitter_username: uvazm_li
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: ziming-li-430b1a138
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/photo.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ziming and I'm a PhD student from University of Amsterdam. 
  
  My research interests are <mark>Information Retrieval<mark>, <mark>Dialogue systems<mark> and <mark>Inverse Reinforcement Learning<mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in computer science some of my other interests and hobbies are:
   - Photography
   - Biking
   - Gaming


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
